# NumPy

## Table on Contents

* [What is an array?](#wiaa)
* [Why use NumPy?](#wun)
* [Let's get started](#lgs)
* Basics
    * [Indexing and slicing](#ias)
    * [Basic array operations](#bao)
    * [Adding, removing, and sorting elements](#arse)
    * [How do you know the shape and size of an array?](#shsiz)
    * [Can you reshape an array?](#resha)


* Array Operations and rules
    * [Broadcasting](#broad)
    * [Creating matrices](#cm)
    * [Aggregation](#aggre)


* Random
    * [Generating random numbers](#grm)


* Array Wrangling
    * [Transposing and reshaping a matrix](#trm)
    * [How to reverse an array](#revers)
    

* Handouts
    * [Reshaping and flattening multidimensional arrays](#reshflat)

<h2><p style="text-align: center;">The fundamental package for scientific computing with Python</p></h2>


<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/NumPy_logo_2020.svg/1920px-NumPy_logo_2020.svg.png" alt="Picture" width="600"/>

Nearly every scientist working in Python draws on the power of NumPy.

NumPy brings the computational power of languages like C and Fortran to Python, a language much easier to learn and use. With this power comes simplicity: a solution in NumPy is often clear and elegant.

![Numpy_scientific](images/Numpy_scientific.png)

---

NumPy's API is the starting point when libraries are written to exploit innovative hardware, create specialized array types, or add capabilities beyond what NumPy provides.

![Numpy_library_integration](images/Numpy_library_integration.png)

-----

NumPy lies at the core of a rich ecosystem of data science libraries. A typical exploratory data science workflow might look like:

![Numpy_DS](https://numpy.org/images/content_images/ds-landscape.png)

- Extract, Transform, Load: Pandas, Intake, PyJanitor
- Exploratory analysis: Jupyter, Seaborn, Matplotlib, Altair
- Model and evaluate: scikit-learn, statsmodels, PyMC3, spaCy
- Report in a dashboard: Dash, Panel, Voila

![Numpy_DS_landscape](https://numpy.org/images/content_images/data-science.png)


For high data volumes, Dask and Ray are designed to scale. Stable deployments rely on data versioning (DVC), experiment tracking (MLFlow), and workflow automation (Airflow and Prefect).


-----
### Numpy for ML
NumPy forms the basis of powerful machine learning libraries like scikit-learn and SciPy. As machine learning grows, so does the list of libraries built on NumPy. TensorFlow’s deep learning capabilities have broad applications — among them speech and image recognition, text-based applications, time-series analysis, and video detection. PyTorch, another deep learning library, is popular among researchers in computer vision and natural language processing. MXNet is another AI package, providing blueprints and templates for deep learning.

![Numpy_ML](https://numpy.org/images/content_images/ml_img/tensorflow-ml-anim.gif)


Statistical techniques called ensemble methods such as binning, bagging, stacking, and boosting are among the ML algorithms implemented by tools such as XGBoost, LightGBM, and CatBoost — one of the fastest inference engines. Yellowbrick and Eli5 offer machine learning visualizations.

----

### What is an array?<a class="anchor" id="wiaa"></a>
An array is a central data structure of the NumPy library. An array is a grid of values and it contains information about the raw data, how to locate an element, and how to interpret an element. It has a grid of elements that can be indexed in various ways. The elements are all of the same type, referred to as the array dtype.

- An array can be indexed by a tuple of nonnegative integers, by booleans, by another array, or by integers. 
- The rank of the array is the number of dimensions. 
- The shape of the array is a tuple of integers giving the size of the array along each dimension.

One way we can initialize NumPy arrays is from Python lists, using nested lists for two- or higher-dimensional data.

----

### Why use NumPy?<a class="anchor" id="wun"></a>
NumPy arrays are faster and more compact than Python lists. An array consumes less memory and is convenient to use. NumPy uses much less memory to store data and it provides a mechanism of specifying the data types. This allows the code to be optimized even further.

----

### What’s the difference between a Python list and a NumPy array?
NumPy gives you an enormous range of fast and efficient ways of creating arrays and manipulating numerical data inside them. While a Python list can contain different data types within a single list, all of the elements in a NumPy array should be homogeneous. The mathematical operations that are meant to be performed on arrays would be extremely inefficient if the arrays weren’t homogeneous.

----

### Let's get started<a class="anchor" id="lgs"></a>

The NumPy library contains multidimensional array and matrix data structures. It provides ndarray, a homogeneous n-dimensional array object, with methods to efficiently operate on it. 

NumPy can be used to perform a wide variety of mathematical operations on arrays. 

It adds powerful data structures to Python that guarantee efficient calculations with arrays and matrices and it supplies an enormous library of high-level mathematical functions that operate on these arrays and matrices.

In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3])

In [3]:
a

array([1, 2, 3])

To create a NumPy array, you can use the function ```np.array()```.

All you need to do to create a simple array is pass a list to it. If you choose to, you can also specify the type of data in your list.

You can visualize your array this way:
![np_array](https://numpy.org/doc/stable/_images/np_array.png)

Besides creating an array from a sequence of elements, you can easily create an array filled with 0’s:

In [4]:
np.zeros(2)

array([0., 0.])

In [5]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

Or an array filled with 1’s:

In [6]:
np.ones(2)

array([1., 1.])

In [7]:
np.ones(20)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [15]:
# You can create an array with a range of elements:
np.arange(4)

array([0, 1, 2, 3])

In [16]:
np.arange(8)

array([0, 1, 2, 3, 4, 5, 6, 7])

And even an array that contains a range of evenly spaced intervals. To do this, you will specify the first number, last number, and the step size.

In [59]:
np.arange(2, 16, 2)

array([ 2,  4,  6,  8, 10, 12, 14])

### Indexing and slicing<a class="anchor" id="ias"></a>
You can index and slice NumPy arrays in the same ways you can slice Python lists.

In [60]:
data = np.array([1, 2, 3])

In [61]:
data[1]

2

In [62]:
data[0:2]

array([1, 2])

In [63]:
data[1:]

array([2, 3])

In [64]:
data[-2:]

array([2, 3])

You can visualize it this way:

![np_array_index](https://numpy.org/doc/stable/_images/np_indexing.png)

You may want to take a section of your array or specific array elements to use in further analysis or additional operations. To do that, you’ll need to subset, slice, and/or index your arrays.

If you want to select values from your array that fulfill certain conditions, it’s straightforward with NumPy.

In [65]:
# For example, if you start with this array:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [66]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [67]:
# You can easily print all of the values in the array that are less than 5.
print(a[a < 5])

[1 2 3 4]


In [68]:
# You can also select, for example, numbers that are equal to or greater than 5, and use that condition to index an array.
five_up = (a >= 5)

In [69]:
five_up

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [70]:
print(a[five_up])

[ 5  6  7  8  9 10 11 12]


In [71]:
# You can select elements that are divisible by 2:
divisible_by_2 = a[a%2==0]

In [72]:
print(divisible_by_2)

[ 2  4  6  8 10 12]


In [73]:
c = a[(a > 2) & (a < 11)]
print(c)

[ 3  4  5  6  7  8  9 10]


In [100]:
five_up = (a > 5) | (a == 5)
print(five_up)

[False False False False False  True]


### Basic array operations<a class="anchor" id="bao"></a>
Once you’ve created your arrays, you can start to work with them. Let’s say, for example, that you’ve created two arrays, one called “data” and one called “ones”

![numpy_maths](https://numpy.org/doc/stable/_images/np_array_dataones.png)

You can add the arrays together with the plus sign.

In [101]:
data = np.array([1, 2])
ones = np.ones(2, dtype=int)

In [102]:
data

array([1, 2])

In [103]:
ones

array([1, 1])

In [104]:
data + ones

array([2, 3])

In [105]:
# You can, of course, do more than just addition!
print(data - ones)
print(data * data)
print(data / data)

[0 1]
[1 4]
[1. 1.]


![numpy_base_maths](https://numpy.org/doc/stable/_images/np_sub_mult_divide.png)

Basic operations are simple with NumPy. If you want to find the sum of the elements in an array, you’d use ```sum()```. This works for 1D arrays, 2D arrays, and arrays in higher dimensions.

In [106]:
a = np.array([1, 2, 3, 4])

a.sum()

10

To add the rows or the columns in a 2D array, you would specify the axis.

If you start with this array:

In [107]:
b = np.array([[1, 1], [2, 2]])

In [108]:
# You can sum over the axis of rows with:
b.sum(axis=0)

array([3, 3])

In [109]:
b.sum(axis=1)

array([2, 4])

### Adding, removing, and sorting elements<a class="anchor" id="arse"></a>
Sorting an element is simple with np.sort(). You can specify the axis, kind, and order when you call the function.

In [110]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

In [111]:
# You can quickly sort the numbers in ascending order with:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [112]:
type(arr)

numpy.ndarray

In [113]:
arr

array([2, 1, 5, 3, 7, 4, 6, 8])

You can concatenate them with ```np.concatenate()```.

In [114]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [115]:
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [116]:
a

array([1, 2, 3, 4])

In [117]:
b

array([5, 6, 7, 8])

### What if we have multi-dimensional data

In [118]:
mul_b = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [119]:
mul_b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [120]:
c = np.array([[20,21,22,23]])

In [121]:
c

array([[20, 21, 22, 23]])

In [122]:
np.concatenate((mul_b, c), axis=0)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [20, 21, 22, 23]])

### Look closely for the difference

In [123]:
d = np.array([1,2,3])

In [124]:
d.shape

(3,)

In [125]:
d

array([1, 2, 3])

In [126]:
e = np.array([[1,2,3]])

In [127]:
e.shape

(1, 3)

In [128]:
e

array([[1, 2, 3]])

### How do you know the shape and size of an array?<a class="anchor" id="shsiz"></a>

```ndarray.ndim``` will tell you the number of axes, or dimensions, of the array.

```ndarray.size``` will tell you the total number of elements of the array. This is the product of the elements of the array’s shape.

```ndarray.shape``` will display a tuple of integers that indicate the number of elements stored along each dimension of the array. If, for example, you have a 2-D array with 2 rows and 3 columns, the shape of your array is (2, 3).

# Only make it 2D

In [129]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])

In [130]:
array_example.ndim

3

In [131]:
array_example.size

24

In [132]:
array_example.shape

(3, 2, 4)

### Can you reshape an array?<a class="anchor" id="resha"></a>
Yes!

Using ```arr.reshape()``` will give a new shape to an array without changing the data. Just remember that when you use the reshape method, the array you want to produce needs to have the same number of elements as the original array. If you start with an array with 12 elements, you’ll need to make sure that your new array also has a total of 12 elements.

In [133]:
# If you start with this array:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [134]:
b = a.reshape(3, 2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


### Broadcasting<a class="anchor" id="broad"></a>
There are times when you might want to carry out an operation between an array and a single number or between arrays of two different sizes. For example, your array (we’ll call it “data”) might contain information about distance in miles but you want to convert the information to kilometers.

In [135]:
# You can perform this operation with:
data = np.array([1.0, 2.0])
data * 1.6

array([1.6, 3.2])

![numpy_broadcast](https://numpy.org/doc/stable/_images/np_multiply_broadcasting.png)

NumPy understands that the multiplication should happen with each cell. That concept is called broadcasting. Broadcasting is a mechanism that allows NumPy to perform operations on arrays of different shapes. The dimensions of your array must be compatible, for example, when the dimensions of both arrays are equal or when one of them is 1. If the dimensions are not compatible, you will get a ```ValueError```.

### More useful array operations
NumPy also performs aggregation functions. In addition to ```min```, ```max```, and ```sum```, you can easily run mean to get the average, prod to get the result of multiplying the elements together, std to get the standard deviation, and more.

In [136]:
data = np.array([1.0, 2.0, 3.0])

In [137]:
data.max()

3.0

In [138]:
data.min()

1.0

In [139]:
data.sum()

6.0

![numpy_agg](https://numpy.org/doc/stable/_images/np_aggregation.png)

In [172]:
# Let’s start with this array, called “a”
# a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
#               [0.54627315, 0.05093587, 0.40067661, 0.55645993],
#               [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

a = np.random.randint(10, size=(4,4))

In [173]:
a

array([[7, 2, 5, 0],
       [2, 2, 1, 7],
       [2, 8, 5, 8],
       [5, 0, 8, 5]])

It’s very common to want to aggregate along a row or column. By default, every NumPy aggregation function will return the aggregate of the entire array. To find the sum or the minimum of the elements in your array, run:

In [174]:
a.sum()

67

In [175]:
a.min()

0

In [176]:
a.min(axis=0)

array([2, 0, 1, 0])

In [177]:
a.min(axis=1)

array([0, 1, 2, 0])

### Creating matrices<a class="anchor" id="cm"></a>
You can pass Python lists of lists to create a 2-D array (or “matrix”) to represent them in NumPy.



In [146]:
data = np.array([[1, 2], [3, 4], [5, 6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

![numpy_matr](https://numpy.org/doc/stable/_images/np_create_matrix.png)

Indexing and slicing operations are useful when you’re manipulating matrices:

In [147]:
data[0, 1]

2

In [148]:
data[1:3]

array([[3, 4],
       [5, 6]])

In [149]:
data[0:2, 0]


array([1, 3])

![numpy_slicer](https://numpy.org/doc/stable/_images/np_matrix_indexing.png)

### Aggregation<a class="anchor" id="aggre"></a>
You can aggregate matrices the same way you aggregated vectors:

In [150]:
data.max()

6

In [151]:
data.min()

1

In [152]:
data.sum()

21

![numpy_aggregate](https://numpy.org/doc/stable/_images/np_matrix_aggregation.png)

You can aggregate all the values in a matrix and you can aggregate them across columns or rows using the axis parameter. To illustrate this point, let’s look at a slightly modified dataset:

In [153]:
data = np.array([[1, 2], [5, 3], [4, 6]])

In [154]:
data

array([[1, 2],
       [5, 3],
       [4, 6]])

In [155]:
data.max(axis=0)

array([5, 6])

In [156]:
data.max(axis=1)

array([2, 5, 6])

![numpy_nax_min](https://numpy.org/doc/stable/_images/np_matrix_aggregation_row.png)

Once you’ve created your matrices, you can add and multiply them using arithmetic operators if you have two matrices that are the same size.

In [157]:
data = np.array([[1, 2], [3, 4]])
ones = np.array([[1, 1], [1, 1]])
data + ones

array([[2, 3],
       [4, 5]])

![np_matrix_arithmetic](https://numpy.org/doc/stable/_images/np_matrix_arithmetic.png)

You can do these arithmetic operations on matrices of different sizes, but only if one matrix has only one column or one row. In this case, NumPy will use its broadcast rules for the operation.

In [158]:
data = np.array([[1, 2], [3, 4], [5, 6]])
ones_row = np.array([[1, 1]])
data + ones_row

array([[2, 3],
       [4, 5],
       [6, 7]])

![np_matrix_broadcasting](https://numpy.org/doc/stable/_images/np_matrix_broadcasting.png)

### Generating random numbers<a class="anchor" id="grm"></a>
The use of random number generation is an important part of the configuration and evaluation of many numerical and machine learning algorithms. Whether you need to randomly initialize weights in an artificial neural network, split data into random sets, or randomly shuffle your dataset, being able to generate random numbers (actually, repeatable pseudo-random numbers) is essential.


### randint will give you a number from 0 upto your number


In [183]:
np.random.randint(100)

26

In [179]:
np.random.randint(100)

87

In [180]:
np.random.randint(100)

18

### What if we need floats.

In [291]:
# Will give between 0 & 1 
np.random.rand()

0.694674759456011

In [293]:
np.random.rand()

0.45361513487732874

In [294]:
np.random.rand()

0.9879989888122344

### What if we need between 0 and 1

In [295]:
np.random.random()

0.9003047103885282

In [296]:
np.random.random()

0.8744701939843474

In [297]:
np.random.random()

0.3633678635953167

### Positive with integer value

In [290]:
np.random.randint(100)

43

![np_ones_zeros_random](https://numpy.org/doc/stable/_images/np_ones_zeros_random.png)


### How to get unique items and counts
You can find the unique elements in an array easily with ```np.unique```.

In [300]:
a = np.array([1,2,3,4,5,6,6,5,4,3,1,2,3,1,2,5,3,4,2])

In [301]:
# you can use np.unique to print the unique values in your array:
unique_values = np.unique(a)
print(unique_values)

[1 2 3 4 5 6]


### Transposing and reshaping a matrix<a class="anchor" id="trm"></a>
It’s common to need to transpose your matrices. NumPy arrays have the property T that allows you to transpose a matrix.

![np_transposing_reshaping](https://numpy.org/doc/stable/_images/np_transposing_reshaping.png)

You may also need to switch the dimensions of a matrix. This can happen when, for example, you have a model that expects a certain input shape that is different from your dataset. This is where the ```reshape``` method can be useful. 

You simply need to pass in the new dimensions that you want for the matrix.

In [302]:
data.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [303]:
data.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

![np_reshape](https://numpy.org/doc/stable/_images/np_reshape.png)

You can also use ```.transpose()``` to reverse or change the axes of an array according to the values you specify.

In [304]:
# If you start with this array:
arr = np.arange(6).reshape((2, 3))
arr

array([[0, 1, 2],
       [3, 4, 5]])

You can transpose your array with ```arr.transpose()```.

In [305]:
arr.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

You can also use ```arr.T```:

In [306]:
arr.T

array([[0, 3],
       [1, 4],
       [2, 5]])

### How to reverse an array<a class="anchor" id="revers"></a>
NumPy’s ```np.flip()``` function allows you to flip, or reverse, the contents of an array along an axis. When using np.flip(), specify the array you would like to reverse and the axis. If you don’t specify the axis, NumPy will reverse the contents along all of the axes of your input array.

**Reversing a 1D array**

In [307]:
# If you begin with a 1D array like this one:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [308]:
# You can reverse it with:
reversed_arr = np.flip(arr)

In [310]:
print(reversed_arr)

[8 7 6 5 4 3 2 1]


# Handouts (Not to be covered in class)

**Reversing a 2D array**

A 2D array works much the same way.

In [ ]:
# If you start with this array:
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
arr_2d

In [ ]:
# You can reverse the content in all of the rows and all of the columns with:
reversed_arr = np.flip(arr_2d)
print(reversed_arr)

In [ ]:
# You can easily reverse only the rows with:
reversed_arr_rows = np.flip(arr_2d, axis=0)
print(reversed_arr_rows)

In [ ]:
# Or reverse only the columns with:
reversed_arr_columns = np.flip(arr_2d, axis=1)
print(reversed_arr_columns)

You can also reverse the contents of only one column or row. For example, you can reverse the contents of the row at index position 1 (the second row):

In [ ]:
arr_2d[1] = np.flip(arr_2d[1])
print(arr_2d)

### Reshaping and flattening multidimensional arrays<a class="anchor" id="reshflat"></a>
There are two popular ways to flatten an array: ```.flatten()``` and ```.ravel()```. The primary difference between the two is that the new array created using ```ravel()``` is actually a reference to the parent array (i.e., a “view”). This means that any changes to the new array will affect the parent array as well. Since ```ravel``` does not create a copy, it’s memory efficient.

In [ ]:
# If you start with this array:
x = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
x

You can use ```flatten``` to flatten your array into a 1D array.

In [ ]:
x.flatten()

When you use ```flatten```, changes to your new array won’t change the parent array.

In [ ]:
a1 = x.flatten()
a1[0] = 99
print(x)  # Original array

In [ ]:
print(a1)  # New array

But when you use ```ravel```, the changes you make to the new array will affect the parent array.

In [ ]:
a2 = x.ravel()
a2[0] = 98
print(x)  # Original array

In [ ]:
print(a2)  # New array